# Generated by Django 4.0.2 on 2022-02-17 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Bookweb', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='author',
            name='average_grade',
        ),
        migrations.AddConstraint(
            model_name='bookgrades',
            constraint=models.UniqueConstraint(fields=('user', 'book'), name='dzieciol'),
        ),
    ]
