# Generated by Django 4.0.2 on 2022-02-23 22:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Bookweb', '0002_remove_author_average_grade_bookgrades_dzieciol'),
    ]

    operations = [
        migrations.CreateModel(
            name='PublicationComments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField(null=True)),
                ('publication', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Bookweb.publication')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddConstraint(
            model_name='publicationcomments',
            constraint=models.UniqueConstraint(fields=('user', 'publication'), name='dzieciol2'),
        ),
    ]
